### ISSUE TITLE
Unable to find a specification for `ZoomableImageSlider`

### ISSUE THREAD

**Issue by emirbeytekin** [vishwas00/ZoomableImageSlider#1]
Analyzing dependencies
[!] Unable to find a specification for `ZoomableImageSlider`

**Comment by vishwas00** [comment]
Can you please provide more details about this because I can't reproduce this issue.

Make sure that you are specifying pod in following way-
pod 'ZoomableImageSlider'

**Comment by vishwas00** [comment]
Please try pod update
