### ISSUE TITLE
zoom image and move to next image 

### ISSUE THREAD

**Issue by kuldipsinh09** [vishwas00/ZoomableImageSlider#2]
- when I zoom one image after that I'm slide next image.but when I slide back that time the previous image is in the zoomable position. when I slide in next image and again go previous image that time reload previous image and set it in actual position like photos application in iPhone.

- image tack some time in loading so you can use kingFisher image loading laibrary  or u can load all image in viewdidload() method for avoid this problem.

**Comment by vishwas00** [comment]
For point1:
Fixed the issue

Point2:
Already using Kingfisher, you can also specify placeholder image

**Comment by kuldipsinh09** [comment]
- when I zoom one image after that I'm slide next image.but when I slide back that time the previous image is in the zoomable position. 

- you can follow any one from bellow given 
1) when one image is in zoomable position that time never slide on next image (like android mobile gallery).
2) when one image is in zoomable position and I am sliding on next or previous image. but when I slide that image which is set a zoomable , on sliding time when I am come back on that image it is need to set in actual position(Like iPhone image gallery)
